// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TFlab - Modified for NY Time zones

//@version=5
indicator("KillZones & Sessions [NY Time] | 7:00-9:00 & 10:00-13:00" , 'NY Time Kill Zones', overlay = true, max_bars_back = 5000, max_boxes_count = 500, max_labels_count = 500, max_lines_count = 500)

// import Sessions and KillZones Library
import TFlab/SessionAndKillZoneLibrary_TradingFinder/1 as Sess

// Global Setting
ShowMoreInfo = input.bool(false, 'Show More Info', inline = 'More' , group = 'Global Setting')
ColorMoreInfo = input.color(#0c3299, '', inline = 'More' , group = 'Global Setting')

//Session 7:00-9:00 AM (UTC-4 time zone)
show_AsiaSess = input(true, '7:00 - 9:00 AM Session',inline = 'ses1', group = '7:00 - 9:00 AM Kill Zone', tooltip = 'Morning Kill Zone 7:00-9:00 AM')
Asia_SessTime = input.session('0700-0900', '',  group = '7:00 - 9:00 AM Kill Zone')
Asia_color = input.color(#fa7b05, '', inline = 'ses1', group = '7:00 - 9:00 AM Kill Zone')
show_AsiaKill = input(true, '7:00 - 9:00 AM Kill Zone', group = '7:00 - 9:00 AM Kill Zone')
Asia_KillTime = input.session('0700-0900', '', group = '7:00 - 9:00 AM Kill Zone')

//Session 10:00 AM - 1:00 PM (UTC-4 time zone)
show_LondonSess = input(true, '10:00 AM - 1:00 PM Session',  inline = 'ses2', group = '10:00 AM - 1:00 PM Kill Zone', tooltip = 'Midday Kill Zone 10:00 AM - 1:00 PM') 
London_SessTime = input.session('1000-1300', '',  group = '10:00 AM - 1:00 PM Kill Zone')
London_color = input.color(#118502, '', inline = 'ses2', group = '10:00 AM - 1:00 PM Kill Zone')
show_LondonKill = input(true, '10:00 AM - 1:00 PM Kill Zone',  group = '10:00 AM - 1:00 PM Kill Zone') 
London_KillTime = input.session('1000-1300', '', group = '10:00 AM - 1:00 PM Kill Zone')

// Call Sessions and KillZones Library
Sess.SessionDetector('7:00 - 9:00 AM'  , Asia_SessTime, Asia_KillTime, show_AsiaSess, show_AsiaKill, 'Session', ShowMoreInfo ,Asia_color,ColorMoreInfo)
Sess.SessionDetector('10:00 AM - 1:00 PM', London_SessTime, London_KillTime, show_LondonSess, show_LondonKill, 'Session', ShowMoreInfo ,London_color,ColorMoreInfo)