//@version=5
// SZT fork of DaviddTech's T3 filter keeping CC BY-NC-SA 4.0 requirements.
// Original license: https://creativecommons.org/licenses/by-nc-sa/4.0/
// © DaviddTech | Modded for SZTrades

indicator(title='SZT T3 Filter', shorttitle='SZT T3', overlay=true, max_lines_count=500)

useT3 = input.bool(true, 'Use T3?')
crossT3 = input.bool(true, 'Cross confirmation? - T3')
inverseT3 = input.bool(false, 'Inverse? - T3')

lengthT3 = input.int(5, 'Length - T3', minval=1)
factorT3 = input.float(0.7, 'Factor - T3', minval=0, maxval=1)
highlightMovementsT3 = input.bool(true, 'Highlight Movements? - T3')
srcT3 = input.source(close, 'Source - T3')

gdT3(src, len) =>
    ta.ema(src, len) * (1 + factorT3) - ta.ema(ta.ema(src, len), len) * factorT3

t3 = gdT3(gdT3(gdT3(srcT3, lengthT3), lengthT3), lengthT3)

t3Color = highlightMovementsT3 ? (t3 > t3[1] ? color.green : color.red) : #6d1e7f

t3Signals = t3 > t3[1] ? 1 : -1
basicLongCondition = t3Signals > 0 and close > t3
basicShortCondition = t3Signals < 0 and close < t3

t3SignalsLong = useT3 ? (highlightMovementsT3 ? basicLongCondition : close > t3) : true
t3SignalsShort = useT3 ? (highlightMovementsT3 ? basicShortCondition : close < t3) : true

t3SignalsLongCross = crossT3 ? (not t3SignalsLong[1] and t3SignalsLong) : t3SignalsLong
t3SignalsShortCross = crossT3 ? (not t3SignalsShort[1] and t3SignalsShort) : t3SignalsShort

t3SignalsLongFinal = inverseT3 ? t3SignalsShortCross : t3SignalsLongCross
t3SignalsShortFinal = inverseT3 ? t3SignalsLongCross : t3SignalsShortCross

plot(t3SignalsLongFinal ? 1 : 0, 'Heartbeat Long', display=display.data_window)
plot(t3SignalsShortFinal ? -1 : 0, 'Heartbeat Short', display=display.data_window)

plot(useT3 ? t3 : na, title='T3', linewidth=2, color=t3Color)
